# .travis.yml

# build using Python 3.6
language: python
python:
  - 3.6
# Cache Dependencies
cache: pip
# we need two Linux packages for the optimize_images plugin

# install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
# build our blog
script:
  - git clone https://github.com/whimian/martin-pelican.git
  - pelican content

# deploy to GitHub pages
deploy:
  provider: pages
  local_dir: output
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  # only deploy on "main" branch
  on:
    branch: master
